### ISSUE TITLE
bookmark notes missing after import of large firefox html file

### ISSUE THREAD

**Issue by bytepipe** [emmyemi/bookmark-notes#12]
Howdy,

I did not even notice that the bookmark notes were taken out. I almost abandoned Firefox as I have a lot of information stored in the notes and losing that about gave me a heart attack. So was nice to find this add-on effort.

I exported my firefox bookmarks to an html file and my notes were verified. I installed the v1.1.1 add-on and imported the html file, but the notes were dropped for anything after a certain point. I cannot tell where I as have a lot of directories dividing up my 2000+ bookmarks. The notes were intact at the beginning in several directories, but totally missing about half way down the bookmark tree. I tried another import attempt with same results.  I then removed roughly half of the html file and re-imported it and the notes appeared for those that had been missing in the first and second attempts.  Not sure if any are missing but the important ones seem to be there on a casual check

So the html file import is not handling large bookmark imports.

Side note: very few of the favicons are imported, even with file trimming and multiple attempts. The default shows up on roughly 90% of the bookmarks

**Comment by emmyemi** [comment]
The add-on gathers all the data to be imported as soon as the file is selected, since pressing the Import button clears the file selection.

With large numbers of bookmarks potentially taking longer to parse, it sounds like we need to make sure everything has been checked before allowing the user to press Import.

Thank you for the report! I'll try to have a fix available as soon as I can.

**Comment by bytepipe** [comment]
@emmyemi - about:* = none. JS exec = none that I'm aware of.

**Comment by emmyemi** [comment]
Since I don't have a large file to work with, this one may need some outside help, unless you'd be willing to provide your exported file for me to test.

In the meantime, the resolution of #16 in version 1.1.3 may also help your case, but if it doesn't, refer to my first statement.

**Comment by emmyemi** [comment]
A recent review stated that the issue with large files had been fixed, so I'm going to mark this as `needs:confirmation` for now. If you could confirm whether it's fixed in your case as well, I'd appreciate it!

**Comment by emmyemi** [comment]
Wonderful! Folder titles not being restricted to a single line seems like an oversight, so I'll be fixing that in the next couple of days. Thank you for the report!
