### ISSUE TITLE
Search field missing

### ISSUE THREAD

**Issue by francwalter** [emmyemi/bookmark-notes#2]
Hallo
to make a description/annotation/note to a existing bookmark, it is difficult to find it yet. There is no (fast-)search field in the Add-On. Should (adjustable) search through url, title and/or tags.

Further the bookmarks in the Sidebar are not good separated visually, only when hovering there is a border.
Further the bookmarks in the Sidebar have the title as title. If the title is missing, it should take the url and not "(No title)".
Further there could be a shortcut to open/close the sidebar.

I guess this is the beginning of this Add-On with great potencial in future!
Thanks yet.

frank

**Comment by emmyemi** [comment]
Fixed in [dev-1.2](/emmyemi/bookmark-notes/tree/dev-1.2) 5cb69c0c6496a868c326242649caa8701c439b87 and awaiting merge once all release goals are completed. 🎉
