### ISSUE TITLE
Icon next to the title

### ISSUE THREAD

**Issue by krabo0om** [emmyemi/bookmark-notes#3]
Thanks for the addon!
I have some bookmarks without any title, just the icon is enough. But in the bookmark notes sidebar there is no icon, so I end up with a lot of "No title" entries.

Displaying the icon next to the title/"no title" would be awesome! something like this:
![mockup](https://user-images.githubusercontent.com/3706149/45411853-9a3e4080-b675-11e8-8524-ec77929492ab.png)

**Comment by RU-DIK** [comment]
+1000 
Icons are very required, Icons need necessarily. Without icons are very difficult to navigate in a continuous undifferentiated text.

**Comment by emmyemi** [comment]
Adding this for the list of features for v1.1. The Bookmarks API doesn't give me clean access to site favicons, but the exported HTML files do—since importing is planned for 1.1 as well, that would likely be the best place to add this.

**Comment by krabo0om** [comment]
There is a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1315616) to add the favicon to the bookmark API.

**Comment by emmyemi** [comment]
Until favicons become part of the bookmarks API, I'm closing this as `fixed` since the option to import favicons is now available.
