### ISSUE TITLE
Import was wonky although it eventually worked

### ISSUE THREAD

**Issue by sooyhwang** [emmyemi/bookmark-notes#32]
On my home computer where my account has admin privilege, everything worked fine. However, on my work computer where I don't have the admin privilege, the import process was a bit wonky. First off, nothing seemed to happen when I clicked the Import button. I opened Bookmark Notes on the sidebar and saw no changes. Then after trying Import a few more times, I clicked a bookmark item and saw my notes were there. But there was no indicator icon next to the bookmarks. I unchecked and checked the corresponding option, then the indicator icons showed up fine.

Just letting you know that it wasn't smooth sailing on my work computer. On my home computer, the Import worked fine in one try and I saw all the notes icons without having to uncheck & check back the option. (Actually that I saw the icons on my home computer first was why I was looking for the notes icons on my work computer as well and when I didn't see them, kept trying Import over and over again.)

**Comment by sooyhwang** [comment]
By the way, thank you so much for writing this add-on. I am very much looking forward to the upcoming Export feature. Keep up the good work! Thank you again!!!

**Comment by emmyemi** [comment]
It seems like the issue here might be that since `storage.set()` and `runtime.sendMessage()` are both asynchronous, there's a chance the two promises could resolve in the wrong order, so while the import likely succeeds, the sidebar receives the message to reload before storage is properly set. Thank you for the report!

**Comment by emmyemi** [comment]
Working on this in tandem with #22.
