### ISSUE TITLE
Search failure

### ISSUE THREAD

**Issue by Migliutin** [emmyemi/bookmark-notes#33]
Using `Abc hij pqr` as keyword string to search a bookmark titled (or having in the notes) `Abcdefg▶hijklmno▶pqrstu` returns no result.

**Comment by emmyemi** [comment]
Are you trying to use the RegExp character range method? If so, they should be enclosed in brackets. `[abcdefghijklmnopqrstu]` (or just `[a-u]`) should match any bookmarks with those characters in the title or URL.

Filtering by note content is currently not available—follow #27 for that.

**Comment by Migliutin** [comment]
No, I wasn't trying to use RegExp — just wanted to search for any bookmark having
- `Abc` AND `hij` AND `pqr`

as **substrings** in **title OR url**.

Therefore I would have expected a bookmark titled `Abcdefg▶hijklmno▶pqrstu` to show up in the resultset

**Comment by Migliutin** [comment]
RegExps are great, but I fear laymen won't appreciate the treat.

Wouldn't it be better to keep things as simple as possibile in the searchbox, maybe allowing power users to enable RegExps by means of a side-located checkbox?

**Comment by emmyemi** [comment]
Perhaps, although I think that proposal should be a separate issue. I'll be closing this one, but feel free to open another about more advanced search methods (or see if your suggestions might fit in with #28).
