### ISSUE TITLE
Notes are not saved after import from html or adding

### ISSUE THREAD

**Issue by kevinh1969** [emmyemi/bookmark-notes#43]
I seem to be having an issue where I can import notes from the html file, and add notes ,but once I close FF and then reopen it the notes are gone.  I'm not a developer, only a user.  Is it possible I don't have something set correctly in FF?

**Comment by emmyemi** [comment]
Hey, thanks for the report! Could you give some info about your OS and version of Firefox? Also, please try reproducing the issue [in a fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles). I'm unable to reproduce it myself, so I want to make sure it's not a broken profile (this can happen from time to time if you've been using the same one for a while).

**Comment by kevinh1969** [comment]
I have Windows 10, FF 63.   I noticed, that if I set FF to not remember history, the notes loose their information.   Setting to remember history keeps them from losing the information.  Sorry if that was listed somewhere and I wasted your time.

**Comment by emmyemi** [comment]
Interesting, I was unaware that this would prevent notes from being stored across sessions. Out of curiosity, do any of your preferences remain intact even with the option to not remember history enabled?
