### ISSUE TITLE
indicator that a note is present

### ISSUE THREAD

**Issue by sygiswult** [emmyemi/bookmark-notes#9]
It'll be a great feature if a bookmark had an icon (or any other graphic indicator, a dot etc.) if a note is present.

**Comment by emmyemi** [comment]
Fixed in [dev-1.2](/emmyemi/bookmark-notes/tree/dev-1.2) c4828b07c9fa8b88c31b1d2f4480d33461f16862 and awaiting merge once all release goals are completed.
